### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by jurim76** [gavika/easy_rsa#1]
1) easy-rsa uses "cn_only" X509 DN model by default, so country,province,city and other vars (except CN) are pretty useless
2) Unable to set CN (hardcoded empty answer by default)
3) Unable to set password for CA
4) Unable to define,produce client requests for signing in role itself
5) Role functionality bound to gavika-openvpn role only

**Comment by bngsudheer** [comment]
Thanks for raising the issues. Issue 1, 2 and 3 can be addressed in the next release. 4 is a design choice. We can look at redesigning in a future release, but not immediately. 5, can be addressed in 1.x release branch. PRs welcome!

**Comment by bngsudheer** [comment]
Stale.
